baseURL = "http://example.org/"
languageCode = "en-us"
title = "Sam Hatfield's Talks"
theme = "reveal-hugo"

[author]
name = "Sam Hatfield"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
